async_slam_toolbox_node:
  ros__parameters:

    # ================= 1. 基础配置 =================
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: false
    
   
    transform_publish_period: 0.02  
    laser_min_range: 0.05
    laser_max_range: 12.0    
    laser_max_angle: 3.14159 
    laser_min_angle: 0       
    resolution: 0.04              
    
    throttle_scans: 1             
    scan_buffer_size: 100        

    # ================= 3. 实时建图与刷新=================
    map_update_interval: 0.2      

    use_online_correlative_scan_matching: true 
    
   
    real_time_correlative_scan_matcher:
      linear_search_window: 0.2
      angular_search_window: 0.5  
      translation_delta_cost_weight: 20.0
      rotation_delta_cost_weight: 1.0
      correlation_search_space_resolution: 0.01

    # ================= 4. 后端优化 (Loop Closure) =================
    do_loop_closing: true
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    POSE_GRAPH:
      constraint_builder:
        min_score: 0.60               
        global_localization_min_score: 0.65
        loop_search_maximum_distance: 15.0 
        
 
    optimize_every_n_nodes: 5
    optimization_step_limit: 0.5

    
    minimum_time_interval: 0.05   
    minimum_travel_distance: 0.05 
    minimum_travel_heading: 0.05  

    # ================= 6. 系统资源 =================
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000